(function () {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s); const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const clone = (v) => JSON.parse(JSON.stringify(v)); const esc = (v = '') => String(v).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
  const split = (v) => Array.isArray(v) ? v : String(v || '').split(',').map((x) => x.trim()).filter(Boolean); const id = () => crypto.randomUUID();
  const config = window.VEYRATH_SUPABASE || {}; const configured = Boolean(/^https:\/\//.test(config.url || '') && config.anonKey && !config.anonKey.includes('YOUR_'));
  let client = null;
  async function connectClient() { if (!configured) return false; if (!window.supabase) { try { await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); }); } catch (_) { return false; } } client = window.supabase.createClient(config.url, config.anonKey); return true; }
  let products = []; let siteData = clone(window.VEYRATH_SITE_DATA || {}); let inquiries = []; let newsletter = [];
  const message = (form, text) => { const node = $('.form-message', form); if (node) node.textContent = text; };
  const openLogin = (note = '') => { $('#adminApp').hidden = true; $('#adminLogin').hidden = false; if (note) message($('#loginForm'), note); };
  const openApp = async () => { $('#adminLogin').hidden = true; $('#adminApp').hidden = false; await loadAll(); };
  const activate = (name) => { $$('.admin-nav button').forEach((b) => b.classList.toggle('is-active', b.dataset.adminTab === name)); $$('.admin-panel').forEach((p) => p.classList.toggle('is-active', p.dataset.adminPanel === name)); scrollTo({ top: 0, behavior: 'smooth' }); };

  async function isAdmin() { if (!client) return false; const { data: user } = await client.auth.getUser(); if (!user?.user) return false; const { data } = await client.from('admin_users').select('user_id').eq('user_id', user.user.id).eq('is_active', true).maybeSingle(); return Boolean(data); }
  async function login(event) { event.preventDefault(); const form = event.currentTarget; if (!client) return message(form, 'The secure Supabase connection is unavailable. Refresh and try again.'); const email = $('#adminEmail').value.trim(); message(form, 'Verifying secure access…'); const { error } = await client.auth.signInWithPassword({ email, password: $('#adminPassword').value }); if (error) return message(form, /invalid login credentials/i.test(error.message) ? 'Supabase did not accept that email and password. Check the Auth user password or use the secure sign-in link below.' : error.message); if (!(await isAdmin())) { await client.auth.signOut(); return message(form, 'Login worked, but this user is not an active VEYRATH admin. Run the admin access SQL supplied with the website.'); } $('#adminPassword').value = ''; await openApp(); }
  async function sendMagicLink() { const form = $('#loginForm'); const email = $('#adminEmail').value.trim(); if (!email) { $('#adminEmail').focus(); return message(form, 'Enter your admin email first.'); } if (!client) return message(form, 'The secure Supabase connection is unavailable. Refresh and try again.'); message(form, 'Requesting a secure sign-in link…'); const redirect = new URL('admin.html', location.href).href; const { error } = await client.auth.signInWithOtp({ email, options: { emailRedirectTo: redirect, shouldCreateUser: false } }); message(form, error ? error.message : 'Secure sign-in link sent. Open it from the same email account.'); }
  async function loadAll() {
    const [catalogue, settings, slides, inbox, audience] = await Promise.all([client.from('products').select('*').order('sort_order', { ascending: false }), client.from('site_settings').select('value').eq('key', 'site_data').maybeSingle(), client.from('hero_slides').select('*').order('sort_order'), client.from('inquiries').select('*').order('created_at', { ascending: false }).limit(250), client.from('newsletter_signups').select('*').order('created_at', { ascending: false }).limit(500)]);
    products = catalogue.data || []; siteData = { ...clone(window.VEYRATH_SITE_DATA || {}), ...(settings.data?.value || {}) }; if (slides.data?.length) siteData.banners = slides.data.map((s) => ({ id: s.id, eyebrow: s.eyebrow, heading: s.heading, text: s.body, image_url: s.image_url, align: s.align })); inquiries = inbox.data || []; newsletter = audience.data || []; renderAll();
  }

  function renderProducts() {
    $('#productsTable').innerHTML = products.map((p) => `<tr><td><img src="${esc(p.image_url || p.front_design_url || 'veyrath-tee.jpg')}" alt=""></td><td><strong>${esc(p.name)}</strong><br><small>${esc(p.category || '')} · ${esc(split(p.tags).join(', '))}</small></td><td>₹${Number(p.price || 0).toLocaleString('en-IN')}</td><td>${p.is_published ? 'Published' : 'Draft'}${p.is_featured ? '<br><small>Featured</small>' : ''}</td><td><div class="table-buttons"><button type="button" data-edit-product="${p.id}" aria-label="Edit ${esc(p.name)}">✎</button><button type="button" data-toggle-product="${p.id}" aria-label="Publish or unpublish ${esc(p.name)}">◐</button><button class="danger" type="button" data-delete-product="${p.id}" aria-label="Delete ${esc(p.name)}">×</button></div></td></tr>`).join('') || '<tr><td colspan="5">No products yet. Add your first VEYRATH piece.</td></tr>';
    $$('[data-edit-product]').forEach((b) => b.addEventListener('click', () => editProduct(b.dataset.editProduct))); $$('[data-toggle-product]').forEach((b) => b.addEventListener('click', async () => { const p = products.find((x) => x.id === b.dataset.toggleProduct); if (!p) return; const { error } = await client.from('products').update({ is_published: !p.is_published }).eq('id', p.id); if (!error) await loadAll(); })); $$('[data-delete-product]').forEach((b) => b.addEventListener('click', async () => { const p = products.find((x) => x.id === b.dataset.deleteProduct); if (p && confirm(`Delete “${p.name}”?`)) { const { error } = await client.from('products').delete().eq('id', p.id); if (!error) await loadAll(); } }));
  }
  function editProduct(productId) { const p = products.find((x) => x.id === productId); if (!p) return; const form = $('#productForm'); Object.entries(p).forEach(([key, value]) => { const field = form.elements[key]; if (!field) return; if (field.type === 'checkbox') field.checked = Boolean(value); else if (field.type !== 'file') field.value = Array.isArray(value) ? value.join(', ') : (value ?? ''); }); $('#productFormTitle').textContent = `Edit ${p.name}`; activate('products'); form.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  function resetProduct() { const form = $('#productForm'); form.reset(); form.elements.id.value = ''; form.elements.rating.value = '4.5'; form.elements.sort_order.value = '0'; form.elements.is_published.checked = true; $('#productFormTitle').textContent = 'Add product'; message(form, ''); }
  function fileData(file) { return new Promise((resolve, reject) => { if (!file) return resolve(''); if (file.size > 2 * 1024 * 1024) return reject(new Error('Use an image smaller than 2 MB.')); const reader = new FileReader(); reader.onerror = () => reject(new Error('Could not read the image.')); reader.onload = () => { const image = new Image(); image.onerror = () => reject(new Error('Unsupported image.')); image.onload = () => { const scale = Math.min(1, 1400 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .84)); }; image.src = reader.result; }; reader.readAsDataURL(file); }); }
  async function submitProduct(event) { event.preventDefault(); const form = event.currentTarget; const raw = Object.fromEntries(new FormData(form)); const existing = products.find((p) => p.id === raw.id); message(form, 'Saving securely…'); try { const uploaded = await fileData(form.elements.image_file.files[0]); const payload = { id: raw.id || id(), name: raw.name.trim(), slug: raw.slug.trim() || raw.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), description: raw.description.trim(), price: Number(raw.price || 0), compare_at_price: Number(raw.compare_at_price || 0), category: raw.category, gender: raw.gender, sizes: split(raw.sizes), colours: split(raw.colours), rating: Number(raw.rating || 0), sort_order: Number(raw.sort_order || 0), image_url: uploaded || raw.image_url.trim() || existing?.image_url || '', front_design_url: raw.front_design_url.trim(), back_design_url: raw.back_design_url.trim(), tags: split(raw.tags), style: split(raw.tags), printrove_sku: raw.printrove_sku.trim(), printrove_product_id: raw.printrove_product_id.trim(), printrove_variant_id: raw.printrove_variant_id.trim(), fulfilment_status: raw.fulfilment_status, external_url: raw.external_url.trim(), is_published: form.elements.is_published.checked, is_featured: form.elements.is_featured.checked }; const { error } = await client.from('products').upsert(payload); if (error) throw error; resetProduct(); await loadAll(); message(form, 'Saved to Supabase.'); } catch (error) { message(form, error.message); } }

  function populateHomepage() { const form = $('#homepageForm'); const h = siteData.hero || {}; const values = { hero_eyebrow: h.eyebrow, hero_heading: h.heading, hero_subheading: h.subheading, primary_label: h.primary_label, primary_link: h.primary_link, secondary_label: h.secondary_label, secondary_link: h.secondary_link, hero_image: h.image_url, about_text: siteData.about_text, marquee_text: siteData.marquee_text, category_intro: siteData.category_intro }; Object.entries(values).forEach(([k, v]) => { if (form.elements[k]) form.elements[k].value = v || ''; }); }
  async function submitHomepage(event) { event.preventDefault(); const form = event.currentTarget; const v = Object.fromEntries(new FormData(form)); siteData.hero = { ...(siteData.hero || {}), eyebrow: v.hero_eyebrow.trim(), heading: v.hero_heading.trim(), subheading: v.hero_subheading.trim(), primary_label: v.primary_label.trim(), primary_link: v.primary_link.trim(), secondary_label: v.secondary_label.trim(), secondary_link: v.secondary_link.trim(), image_url: v.hero_image.trim() }; siteData.about_text = v.about_text.trim(); siteData.marquee_text = v.marquee_text.trim(); siteData.category_intro = v.category_intro.trim(); const { error } = await client.from('site_settings').upsert({ key: 'site_data', value: siteData, is_public: true }); message(form, error ? error.message : 'Homepage saved to Supabase.'); }
  function renderBanners() { const banners = siteData.banners || []; $('#bannerList').innerHTML = banners.map((b) => `<div class="banner-row"><img src="${esc(b.image_url || 'veyrath-hero.jpg')}" alt=""><div><strong>${esc(b.heading)}</strong><small>${esc(b.eyebrow || '')}</small></div><button class="danger" type="button" data-delete-banner="${b.id}">Remove</button></div>`).join('') || '<p>No banners yet.</p>'; $$('[data-delete-banner]').forEach((b) => b.addEventListener('click', async () => { const { error } = await client.from('hero_slides').delete().eq('id', b.dataset.deleteBanner); if (!error) await loadAll(); })); }
  async function submitBanner(event) { event.preventDefault(); const form = event.currentTarget; const v = Object.fromEntries(new FormData(form)); const { error } = await client.from('hero_slides').insert({ eyebrow: v.eyebrow.trim(), heading: v.heading.trim(), body: v.text.trim(), image_url: v.image_url.trim(), align: v.align || 'left', is_published: true, sort_order: (siteData.banners || []).length }); if (error) return message(form, error.message); form.reset(); await loadAll(); message(form, 'Carousel banner added.'); }
  function renderRecords() { $('#inquiryList').innerHTML = inquiries.map((x) => `<article class="data-row"><small>${new Date(x.created_at).toLocaleString('en-IN')} · ${esc(x.subject || 'Inquiry')}</small><strong>${esc(x.name || 'Anonymous')} · ${esc(x.email || '')}</strong><span>${esc(x.product || '')}</span><p>${esc(x.message || '')}</p></article>`).join('') || '<p>No inquiries yet.</p>'; $('#newsletterList').innerHTML = newsletter.map((x) => `<article class="data-row"><small>${new Date(x.created_at).toLocaleString('en-IN')}</small><strong>${esc(x.email)}</strong></article>`).join('') || '<p>No newsletter signups yet.</p>'; $('#statInquiries').textContent = inquiries.length; $('#statNewsletter').textContent = newsletter.length; }
  function renderAll() { $('#statProducts').textContent = products.length; $('#statPublished').textContent = products.filter((p) => p.is_published).length; renderProducts(); populateHomepage(); renderBanners(); renderRecords(); }

  function download(name, text, type = 'text/javascript') { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  const exportProducts = () => download('products.js', `/* VEYRATH catalogue export — ${new Date().toISOString()} */\n(function(){window.VEYRATH_PRODUCTS=${JSON.stringify(products, null, 2)};})();\n`);
  const exportSite = () => download('site-data.js', `/* VEYRATH site export — ${new Date().toISOString()} */\n(function(){window.VEYRATH_SITE_DATA=${JSON.stringify(siteData, null, 2)};})();\n`);
  async function importData(event) { event.preventDefault(); const form = event.currentTarget; try { const parsed = JSON.parse($('#importJson').value); const importedProducts = Array.isArray(parsed) ? parsed : parsed.products; if (Array.isArray(importedProducts) && importedProducts.length) { const normalized = importedProducts.map((p) => ({ ...p, id: /^[0-9a-f-]{36}$/i.test(p.id || '') ? p.id : id() })); const { error } = await client.from('products').upsert(normalized); if (error) throw error; } if (parsed.siteData) { const { error } = await client.from('site_settings').upsert({ key: 'site_data', value: parsed.siteData, is_public: true }); if (error) throw error; } await loadAll(); message(form, 'Data imported to Supabase.'); } catch (error) { message(form, `Import failed: ${error.message}`); } }
  function bind() { $('#loginForm').addEventListener('submit', login); $('#adminMagicLink').addEventListener('click', sendMagicLink); $('#adminLogout').addEventListener('click', async () => { await client?.auth.signOut(); openLogin('Signed out.'); }); $$('.admin-nav button').forEach((b) => b.addEventListener('click', () => activate(b.dataset.adminTab))); $$('[data-open-products]').forEach((b) => b.addEventListener('click', () => activate('products'))); $('#productForm').addEventListener('submit', submitProduct); $('#productReset').addEventListener('click', resetProduct); $('#homepageForm').addEventListener('submit', submitHomepage); $('#bannerForm').addEventListener('submit', submitBanner); $('#importForm').addEventListener('submit', importData); $('#exportProducts').addEventListener('click', exportProducts); $('#exportSite').addEventListener('click', exportSite); $('#exportJson').addEventListener('click', () => download('veyrath-data.json', JSON.stringify({ products, siteData }, null, 2), 'application/json')); $('#clearLocalData').addEventListener('click', () => { localStorage.clear(); message($('#importForm'), 'Browser-only cache cleared. Supabase data is unchanged.'); }); }
  async function init() { bind(); if (!(await connectClient())) return openLogin(configured ? 'Could not load the secure Supabase connection. Check your internet connection or content blocker, then refresh.' : 'Configure supabase-config.js to enable secure admin login.'); const { data } = await client.auth.getSession(); if (data.session && await isAdmin()) return openApp(); openLogin(); }
  init();
})();
