(function () {
  'use strict';
  const KEYS = { products: 'veyrath_products_v3', site: 'veyrath_site_data_v3', inquiries: 'veyrath_inquiries_v3', newsletter: 'veyrath_newsletter_v3' };
  const SESSION = 'veyrath_admin_session_v3';
  const $ = (s, root = document) => root.querySelector(s); const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const clone = (v) => JSON.parse(JSON.stringify(v)); const esc = (v = '') => String(v).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
  const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? clone(fallback); } catch (_) { return clone(fallback); } };
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value)); const split = (v) => String(v || '').split(',').map((x) => x.trim()).filter(Boolean);
  const id = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  let products = []; let siteData = {};

  function defaults() { return { products: clone(window.VEYRATH_PRODUCTS || []), site: clone(window.VEYRATH_SITE_DATA || {}) }; }
  function load() { const d = defaults(); products = read(KEYS.products, d.products); siteData = read(KEYS.site, d.site); renderAll(); }
  function message(form, text) { $('.form-message', form).textContent = text; }
  function activate(name) { $$('.admin-nav button').forEach((b) => b.classList.toggle('is-active', b.dataset.adminTab === name)); $$('.admin-panel').forEach((p) => p.classList.toggle('is-active', p.dataset.adminPanel === name)); scrollTo({ top: 0, behavior: 'smooth' }); }
  function openApp() { $('#adminLogin').hidden = true; $('#adminApp').hidden = false; load(); }
  function openLogin() { $('#adminApp').hidden = true; $('#adminLogin').hidden = false; $('#adminPin').value = ''; }

  function renderProducts() {
    $('#productsTable').innerHTML = products.map((p) => `<tr><td><img src="${esc(p.image_url || p.front_design_url || 'veyrath-tee.jpg')}" alt=""></td><td><strong>${esc(p.name)}</strong><br><small>${esc(p.category || '')} · ${esc((p.tags || []).toString())}</small></td><td>₹${Number(p.price || 0).toLocaleString('en-IN')}</td><td>${p.is_published !== false ? 'Published' : 'Draft'}${p.is_featured ? '<br><small>Featured</small>' : ''}</td><td><div class="table-buttons"><button type="button" data-edit-product="${esc(p.id)}" aria-label="Edit ${esc(p.name)}">✎</button><button type="button" data-toggle-product="${esc(p.id)}" aria-label="Publish or unpublish ${esc(p.name)}">◐</button><button class="danger" type="button" data-delete-product="${esc(p.id)}" aria-label="Delete ${esc(p.name)}">×</button></div></td></tr>`).join('') || '<tr><td colspan="5">No products yet. Add your first real VEYRATH piece.</td></tr>';
    $$('[data-edit-product]').forEach((b) => b.addEventListener('click', () => editProduct(b.dataset.editProduct)));
    $$('[data-toggle-product]').forEach((b) => b.addEventListener('click', () => { const p = products.find((x) => String(x.id) === b.dataset.toggleProduct); if (p) { p.is_published = p.is_published === false; saveProducts(); } }));
    $$('[data-delete-product]').forEach((b) => b.addEventListener('click', () => { const p = products.find((x) => String(x.id) === b.dataset.deleteProduct); if (p && confirm(`Delete “${p.name}”?`)) { products = products.filter((x) => x !== p); saveProducts(); } }));
  }

  function editProduct(productId) {
    const p = products.find((x) => String(x.id) === String(productId)); if (!p) return; const form = $('#productForm');
    Object.entries(p).forEach(([key, value]) => { const field = form.elements[key]; if (!field) return; if (field.type === 'checkbox') field.checked = Boolean(value); else if (field.type !== 'file') field.value = Array.isArray(value) ? value.join(', ') : (value ?? ''); });
    $('#productFormTitle').textContent = `Edit ${p.name}`; activate('products'); form.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  function resetProduct() { const form = $('#productForm'); form.reset(); form.elements.id.value = ''; form.elements.rating.value = '4.5'; form.elements.sort_order.value = '0'; form.elements.is_published.checked = true; $('#productFormTitle').textContent = 'Add product'; message(form, ''); }
  function fileData(file) { return new Promise((resolve, reject) => { if (!file) return resolve(''); if (file.size > 2 * 1024 * 1024) return reject(new Error('Please use an image smaller than 2 MB.')); const reader = new FileReader(); reader.onerror = () => reject(new Error('Could not read the image.')); reader.onload = () => { const image = new Image(); image.onerror = () => reject(new Error('That image format could not be processed.')); image.onload = () => { const scale = Math.min(1, 1400 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .84)); }; image.src = reader.result; }; reader.readAsDataURL(file); }); }
  async function submitProduct(event) {
    event.preventDefault(); const form = event.currentTarget; const raw = Object.fromEntries(new FormData(form)); const existing = products.find((p) => String(p.id) === String(raw.id)); message(form, 'Saving…');
    try { const uploaded = await fileData(form.elements.image_file.files[0]); const product = { ...existing, id: raw.id || id(), name: raw.name.trim(), slug: raw.slug.trim() || raw.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), description: raw.description.trim(), price: Number(raw.price || 0), compare_at_price: Number(raw.compare_at_price || 0), category: raw.category, gender: raw.gender, sizes: split(raw.sizes), colours: split(raw.colours), rating: Number(raw.rating || 0), sort_order: Number(raw.sort_order || 0), image_url: uploaded || raw.image_url.trim() || existing?.image_url || '', front_design_url: raw.front_design_url.trim(), back_design_url: raw.back_design_url.trim(), tags: split(raw.tags), style: split(raw.tags), printrove_sku: raw.printrove_sku.trim(), printrove_product_id: raw.printrove_product_id.trim(), printrove_variant_id: raw.printrove_variant_id.trim(), fulfilment_status: raw.fulfilment_status, external_url: raw.external_url.trim(), is_published: form.elements.is_published.checked, is_featured: form.elements.is_featured.checked, updated_at: new Date().toISOString() };
      if (existing) Object.assign(existing, product); else products.unshift(product); write(KEYS.products, products); resetProduct(); message(form, 'Saved locally. Export products.js to publish.'); renderAll();
    } catch (error) { message(form, error.message); }
  }
  function saveProducts() { write(KEYS.products, products); renderAll(); }

  function populateHomepage() { const form = $('#homepageForm'); const hero = siteData.hero || {}; const values = { hero_eyebrow: hero.eyebrow, hero_heading: hero.heading, hero_subheading: hero.subheading, primary_label: hero.primary_label, primary_link: hero.primary_link, secondary_label: hero.secondary_label, secondary_link: hero.secondary_link, hero_image: hero.image_url, about_text: siteData.about_text, marquee_text: siteData.marquee_text, category_intro: siteData.category_intro }; Object.entries(values).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value || ''; }); }
  function submitHomepage(event) { event.preventDefault(); const form = event.currentTarget; const v = Object.fromEntries(new FormData(form)); siteData.hero = { ...(siteData.hero || {}), eyebrow: v.hero_eyebrow.trim(), heading: v.hero_heading.trim(), subheading: v.hero_subheading.trim(), primary_label: v.primary_label.trim(), primary_link: v.primary_link.trim(), secondary_label: v.secondary_label.trim(), secondary_link: v.secondary_link.trim(), image_url: v.hero_image.trim() }; siteData.about_text = v.about_text.trim(); siteData.marquee_text = v.marquee_text.trim(); siteData.category_intro = v.category_intro.trim(); write(KEYS.site, siteData); message(form, 'Homepage content saved locally.'); }
  function renderBanners() { const banners = siteData.banners || []; $('#bannerList').innerHTML = banners.map((b) => `<div class="banner-row"><img src="${esc(b.image_url || 'veyrath-hero.jpg')}" alt=""><div><strong>${esc(b.heading)}</strong><small>${esc(b.eyebrow || '')}</small></div><button class="danger" type="button" data-delete-banner="${esc(b.id)}">Remove</button></div>`).join('') || '<p>No banners yet.</p>'; $$('[data-delete-banner]').forEach((b) => b.addEventListener('click', () => { siteData.banners = banners.filter((x) => String(x.id) !== b.dataset.deleteBanner); write(KEYS.site, siteData); renderBanners(); })); }
  function submitBanner(event) { event.preventDefault(); const form = event.currentTarget; const v = Object.fromEntries(new FormData(form)); siteData.banners = siteData.banners || []; siteData.banners.push({ id: id(), eyebrow: v.eyebrow.trim(), heading: v.heading.trim(), text: v.text.trim(), image_url: v.image_url.trim() }); write(KEYS.site, siteData); form.reset(); message(form, 'Banner added locally.'); renderBanners(); }

  function renderRecords() { const inquiries = read(KEYS.inquiries, []); const newsletter = read(KEYS.newsletter, []); $('#inquiryList').innerHTML = inquiries.map((x) => `<article class="data-row"><small>${new Date(x.created_at).toLocaleString('en-IN')} · ${esc(x.subject || 'Inquiry')}</small><strong>${esc(x.name || 'Anonymous')} · ${esc(x.email || '')}</strong><span>${esc(x.product || '')}</span><p>${esc(x.message || '')}</p></article>`).join('') || '<p>No local inquiries yet.</p>'; $('#newsletterList').innerHTML = newsletter.map((x) => `<article class="data-row"><small>${new Date(x.created_at).toLocaleString('en-IN')}</small><strong>${esc(x.email)}</strong></article>`).join('') || '<p>No local newsletter signups yet.</p>'; $('#statInquiries').textContent = inquiries.length; $('#statNewsletter').textContent = newsletter.length; }
  function renderAll() { $('#statProducts').textContent = products.length; $('#statPublished').textContent = products.filter((p) => p.is_published !== false).length; renderProducts(); populateHomepage(); renderBanners(); renderRecords(); }

  function download(name, text, type = 'text/javascript') { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  function exportProducts() { download('products.js', `/* VEYRATH catalogue export — ${new Date().toISOString()} */\n(function(){\n  window.VEYRATH_PRODUCTS = ${JSON.stringify(products, null, 2)};\n})();\n`); }
  function exportSite() { download('site-data.js', `/* VEYRATH site content export — ${new Date().toISOString()} */\n(function(){\n  window.VEYRATH_SITE_DATA = ${JSON.stringify(siteData, null, 2)};\n})();\n`); }
  function importData(event) { event.preventDefault(); const form = event.currentTarget; try { const parsed = JSON.parse($('#importJson').value); if (Array.isArray(parsed)) products = parsed; else { if (Array.isArray(parsed.products)) products = parsed.products; if (parsed.siteData && typeof parsed.siteData === 'object') siteData = parsed.siteData; } write(KEYS.products, products); write(KEYS.site, siteData); message(form, 'Data imported locally.'); renderAll(); } catch (error) { message(form, `Import failed: ${error.message}`); } }
  function clearData() { if (!confirm('Clear all local VEYRATH admin edits, inquiries and newsletter entries?')) return; Object.values(KEYS).forEach((key) => localStorage.removeItem(key)); load(); }

  function bind() {
    $('#loginForm').addEventListener('submit', (event) => { event.preventDefault(); const form = event.currentTarget; if ($('#adminPin').value === 'veyrath-admin') { sessionStorage.setItem(SESSION, 'yes'); openApp(); } else message(form, 'Access denied.'); });
    $('#adminLogout').addEventListener('click', () => { sessionStorage.removeItem(SESSION); openLogin(); });
    $$('.admin-nav button').forEach((b) => b.addEventListener('click', () => activate(b.dataset.adminTab))); $$('[data-open-products]').forEach((b) => b.addEventListener('click', () => activate('products')));
    $('#productForm').addEventListener('submit', submitProduct); $('#productReset').addEventListener('click', resetProduct); $('#homepageForm').addEventListener('submit', submitHomepage); $('#bannerForm').addEventListener('submit', submitBanner); $('#importForm').addEventListener('submit', importData);
    $('#exportProducts').addEventListener('click', exportProducts); $('#exportSite').addEventListener('click', exportSite); $('#exportJson').addEventListener('click', () => download('veyrath-data.json', JSON.stringify({ products, siteData }, null, 2), 'application/json')); $('#clearLocalData').addEventListener('click', clearData);
  }
  bind(); sessionStorage.getItem(SESSION) === 'yes' ? openApp() : openLogin();
})();
