(function () {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s); const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const esc = (v = '') => String(v).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
  const split = (v) => Array.isArray(v) ? v : String(v || '').split(',').map((x) => x.trim()).filter(Boolean);
  const clone = (value) => JSON.parse(JSON.stringify(value)); const uuid = () => crypto.randomUUID();
  const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value) || 0);
  const config = window.VEYRATH_SUPABASE || {}; const configured = Boolean(/^https:\/\//.test(config.url || '') && config.anonKey && !config.anonKey.includes('YOUR_'));
  const projectRef = (() => { try { return new URL(config.url).hostname.split('.')[0]; } catch (_) { return ''; } })();
  const storageKey = `veyrath-admin-${projectRef || 'unconfigured'}-auth`;
  let client = null; let products = []; let orders = []; let inquiries = []; let newsletter = []; let siteData = clone(window.VEYRATH_SITE_DATA || {});

  function message(form, text) { const node = $('.form-message', form); if (node) node.textContent = text; }
  function status(text, tone = '') { const node = $('#ordersStatus'); if (node) { node.textContent = text; node.dataset.tone = tone; } }
  function activate(name) { $$('.admin-nav button').forEach((b) => b.classList.toggle('is-active', b.dataset.adminTab === name)); $$('.admin-panel').forEach((p) => p.classList.toggle('is-active', p.dataset.adminPanel === name)); scrollTo({ top: 0, behavior: 'smooth' }); }
  function openLogin(note = '') { $('#adminApp').hidden = true; $('#adminLogin').hidden = false; if (note) message($('#loginForm'), note); }
  async function openApp() { $('#adminLogin').hidden = true; $('#adminApp').hidden = false; await loadAll(); }

  function ensureLoginHelpers() {
    const form = $('#loginForm');
    const chip = document.createElement('p'); chip.className = 'admin-project-chip'; chip.id = 'adminProjectStatus'; chip.textContent = configured ? `Connected Supabase project: ${projectRef}` : 'Supabase project is not configured.'; form.querySelector('h1').insertAdjacentElement('afterend', chip);
    const button = document.createElement('button'); button.className = 'admin-session-reset'; button.id = 'adminClearSession'; button.type = 'button'; button.textContent = 'Clear saved Supabase session'; $('#adminMagicLink').insertAdjacentElement('afterend', button);
  }
  async function connectClient() {
    if (!configured) return false;
    if (!window.supabase) await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); });
    client = window.supabase.createClient(config.url, config.anonKey, { auth: { detectSessionInUrl: true, persistSession: true, autoRefreshToken: true, storageKey } }); return true;
  }
  async function isAdmin() { const { data: user } = await client.auth.getUser(); if (!user?.user) return false; const { data } = await client.from('admin_users').select('user_id').eq('user_id', user.user.id).eq('is_active', true).maybeSingle(); return Boolean(data); }
  async function login(event) { event.preventDefault(); const form = event.currentTarget; message(form, 'Verifying secure access…'); const { error } = await client.auth.signInWithPassword({ email: $('#adminEmail').value.trim(), password: $('#adminPassword').value }); if (error) return message(form, /invalid login credentials/i.test(error.message) ? `Supabase rejected this login inside project ${projectRef}. Verify the VEYRATH project and Auth user.` : error.message); if (!(await isAdmin())) { await client.auth.signOut(); return message(form, 'Login worked, but this user is not an active VEYRATH admin. Run admin-access.sql in this project.'); } $('#adminPassword').value = ''; await openApp(); }
  async function magicLink() { const email = $('#adminEmail').value.trim(); if (!email) return message($('#loginForm'), 'Enter your admin email first.'); message($('#loginForm'), 'Requesting a secure sign-in link…'); const { error } = await client.auth.signInWithOtp({ email, options: { emailRedirectTo: new URL('admin.html', location.href).href, shouldCreateUser: false } }); message($('#loginForm'), error ? error.message : `Secure sign-in link sent from project ${projectRef}.`); }
  function clearSession() { Object.keys(localStorage).filter((key) => key === storageKey || key.startsWith('sb-') || key.startsWith('veyrath-admin-')).forEach((key) => localStorage.removeItem(key)); message($('#loginForm'), 'Saved Supabase sessions cleared. Refresh before signing in again.'); }

  async function loadAll() {
    status('Refreshing secure data…');
    const [catalogue, orderData, settings, slides, inbox, audience] = await Promise.all([
      client.from('admin_products').select('*').order('sort_order', { ascending: false }),
      client.from('orders').select('*,order_items(*)').order('created_at', { ascending: false }).limit(500),
      client.from('site_settings').select('value').eq('key', 'site_data').maybeSingle(),
      client.from('hero_slides').select('*').order('sort_order'),
      client.from('inquiries').select('*').order('created_at', { ascending: false }).limit(250),
      client.from('newsletter_signups').select('*').order('created_at', { ascending: false }).limit(500),
    ]);
    const firstError = [catalogue, orderData, settings, slides, inbox, audience].find((result) => result.error)?.error;
    if (firstError) { status(firstError.message, 'error'); throw firstError; }
    products = catalogue.data || []; orders = orderData.data || []; inquiries = inbox.data || []; newsletter = audience.data || [];
    siteData = { ...clone(window.VEYRATH_SITE_DATA || {}), ...(settings.data?.value || {}) };
    if (slides.data?.length) siteData.banners = slides.data.map((slide) => ({ id: slide.id, eyebrow: slide.eyebrow, heading: slide.heading, text: slide.body, image_url: slide.image_url, align: slide.align }));
    renderAll(); status(`Updated ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}.`);
  }

  function profit(product) { const selling = Number(product.selling_price) > 0 ? Number(product.selling_price) : Number(product.price); return selling - Number(product.base_cost || 0) - Number(product.shipping_cost || 0); }
  function renderProducts() {
    $('#productsTable').innerHTML = products.map((p) => `<tr><td><img src="${esc(p.image_url || p.front_design_url || 'veyrath-tee.jpg')}" alt=""></td><td><strong>${esc(p.name)}</strong><br><small>${esc(p.category)} · ${p.is_published ? 'Published' : 'Draft'}</small></td><td>${money(Number(p.selling_price) || p.price)}<br><small>Profit ${money(profit(p))}</small></td><td><span class="status-pill status-${p.fulfilment_status}">${esc(p.fulfilment_status)}</span><br><small>${esc(p.printrove_sku || 'No SKU')}</small></td><td><div class="table-buttons"><button type="button" data-edit-product="${p.id}" aria-label="Edit ${esc(p.name)}">Edit</button><button type="button" data-toggle-product="${p.id}">${p.is_published ? 'Draft' : 'Publish'}</button><button class="danger" type="button" data-delete-product="${p.id}">Delete</button></div></td></tr>`).join('') || '<tr><td colspan="5">No products yet.</td></tr>';
  }
  function editProduct(productId) { const product = products.find((p) => p.id === productId); if (!product) return; const form = $('#productForm'); Object.entries(product).forEach(([key, value]) => { const field = form.elements[key]; if (!field || field.type === 'file') return; if (field.type === 'checkbox') field.checked = Boolean(value); else if (key === 'printrove_variant_map') field.value = JSON.stringify(value || {}, null, 2); else field.value = Array.isArray(value) ? value.join(', ') : (value ?? ''); }); form.elements.profit_estimate.value = money(profit(product)); $('#productFormTitle').textContent = `Edit ${product.name}`; activate('products'); form.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  function resetProduct() { const form = $('#productForm'); form.reset(); form.elements.id.value = ''; form.elements.rating.value = '4.5'; form.elements.sort_order.value = '0'; form.elements.profit_estimate.value = '₹0'; form.elements.is_published.checked = true; $('#productFormTitle').textContent = 'Add product'; message(form, ''); }
  function updateProfit() { const form = $('#productForm'); const selling = Number(form.elements.selling_price.value) || Number(form.elements.price.value); form.elements.profit_estimate.value = money(selling - Number(form.elements.base_cost.value || 0) - Number(form.elements.shipping_cost.value || 0)); }
  function fileData(file) { return new Promise((resolve, reject) => { if (!file) return resolve(''); if (file.size > 2 * 1024 * 1024) return reject(new Error('Use an image smaller than 2 MB.')); const reader = new FileReader(); reader.onerror = () => reject(new Error('Could not read image.')); reader.onload = () => { const image = new Image(); image.onerror = () => reject(new Error('Unsupported image.')); image.onload = () => { const scale = Math.min(1, 1400 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .84)); }; image.src = reader.result; }; reader.readAsDataURL(file); }); }
  async function submitProduct(event) {
    event.preventDefault(); const form = event.currentTarget; const raw = Object.fromEntries(new FormData(form)); const existing = products.find((p) => p.id === raw.id); message(form, 'Saving securely…');
    try {
      let variantMap = {}; if (raw.printrove_variant_map.trim()) { variantMap = JSON.parse(raw.printrove_variant_map); if (!variantMap || Array.isArray(variantMap) || typeof variantMap !== 'object') throw new Error('Variant map must be a JSON object.'); }
      const uploaded = await fileData(form.elements.image_file.files[0]); const selling = Number(raw.selling_price || 0); const base = Number(raw.base_cost || 0); const shipping = Number(raw.shipping_cost || 0);
      const payload = { id: raw.id || uuid(), name: raw.name.trim(), slug: raw.slug.trim() || raw.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), description: raw.description.trim(), price: Number(raw.price), selling_price: selling, compare_at_price: Number(raw.compare_at_price || 0), currency: 'INR', category: raw.category, gender: raw.gender, sizes: split(raw.sizes), colours: split(raw.colours), tags: split(raw.tags), style: split(raw.tags), rating: Number(raw.rating || 0), sort_order: Number(raw.sort_order || 0), image_url: uploaded || raw.image_url.trim() || existing?.image_url || '', front_design_url: raw.front_design_url.trim(), back_design_url: raw.back_design_url.trim(), printrove_sku: raw.printrove_sku.trim(), printrove_product_id: raw.printrove_product_id.trim(), printrove_variant_id: raw.printrove_variant_id.trim(), printrove_variant_map: variantMap, printrove_product_type: raw.printrove_product_type.trim(), print_type: raw.print_type.trim(), base_cost: base, shipping_cost: shipping, profit_margin: (selling || Number(raw.price)) - base - shipping, fulfilment_status: raw.fulfilment_status, external_url: raw.external_url.trim(), is_published: form.elements.is_published.checked, is_featured: form.elements.is_featured.checked };
      const { error } = await client.from('products').upsert(payload); if (error) throw error; resetProduct(); await loadAll(); message(form, 'Product saved to Supabase.');
    } catch (error) { message(form, error.message); }
  }

  function orderVisible(order, filter) { if (filter === 'paid') return order.payment_status === 'paid'; if (filter === 'pending') return order.payment_status === 'pending'; if (filter === 'printrove_failed') return order.fulfilment_status === 'printrove_failed'; if (filter === 'admin_hold') return order.admin_hold; return true; }
  function renderOrders() {
    const filter = $('#orderFilter').value; const visible = orders.filter((order) => orderVisible(order, filter));
    $('#ordersTable').innerHTML = visible.map((order) => {
      const items = (order.order_items || []).map((item) => `${item.quantity}× ${esc(item.product_name)} <small>${esc(item.colour)} / ${esc(item.size)}</small>`).join('<br>');
      const canSend = order.payment_status === 'paid' && !order.admin_hold && ['not_sent', 'printrove_failed'].includes(order.fulfilment_status);
      return `<tr><td><strong>${esc(order.order_number)}</strong><br><small>${new Date(order.created_at).toLocaleString('en-IN')}</small></td><td><strong>${esc(order.customer_name)}</strong><br><small>${esc(order.customer_phone)} · ${esc(order.customer_email)}</small><br><small>${esc([order.address_line1,order.address_line2,order.city,order.state,order.pincode].filter(Boolean).join(', '))}</small></td><td>${items || 'No items'}</td><td><span class="status-pill status-${esc(order.payment_status)}">${esc(order.payment_status)}</span>${order.razorpay_payment_id ? `<br><small>${esc(order.razorpay_payment_id)}</small>` : ''}</td><td><span class="status-pill status-${esc(order.fulfilment_status)}">${esc(order.fulfilment_status)}</span>${order.printrove_order_id ? `<br><small>ID ${esc(order.printrove_order_id)} · ${esc(order.printrove_status || '')}</small>` : ''}${order.admin_hold ? '<br><span class="hold-note">Manual hold</span>' : ''}</td><td><strong>${money(order.total_amount)}</strong><br><small>Shipping ${money(order.shipping_amount)}</small></td><td><div class="order-actions">${canSend ? `<button class="primary" type="button" data-send-printrove="${order.id}">${order.fulfilment_status === 'printrove_failed' ? 'Retry Printrove' : 'Send to Printrove'}</button>` : ''}${order.printrove_order_id ? `<button type="button" data-sync-printrove="${order.id}">Sync status</button>` : ''}<button type="button" data-toggle-hold="${order.id}">${order.admin_hold ? 'Release hold' : 'Mark issue / hold'}</button></div></td></tr>`;
    }).join('') || '<tr><td colspan="7">No orders match this filter.</td></tr>';
  }
  async function functionMessage(error, fallback) { try { const body = await error?.context?.json(); return body?.error || fallback; } catch (_) { return error?.message || fallback; } }
  async function invokeOrderFunction(name, orderId) { status(`${name === 'send-to-printrove' ? 'Sending to Printrove' : 'Syncing status'}…`); const { data, error } = await client.functions.invoke(name, { body: { order_id: orderId } }); if (error || !data?.success) throw new Error(await functionMessage(error, data?.error || 'Function request failed.')); await loadAll(); return data; }
  async function orderAction(event) {
    const send = event.target.closest('[data-send-printrove]'); const sync = event.target.closest('[data-sync-printrove]'); const hold = event.target.closest('[data-toggle-hold]'); if (!send && !sync && !hold) return;
    try {
      if (send) { const order = orders.find((item) => item.id === send.dataset.sendPrintrove); if (!confirm(`Send paid order ${order?.order_number || ''} to Printrove now?`)) return; send.disabled = true; await invokeOrderFunction('send-to-printrove', send.dataset.sendPrintrove); status('Printrove order created.', 'success'); }
      if (sync) { sync.disabled = true; await invokeOrderFunction('sync-printrove-status', sync.dataset.syncPrintrove); status('Printrove status updated.', 'success'); }
      if (hold) { const order = orders.find((item) => item.id === hold.dataset.toggleHold); const { error } = await client.from('orders').update({ admin_hold: !order.admin_hold, notes: !order.admin_hold ? `${order.notes || ''}\nManual hold set ${new Date().toISOString()}`.trim() : order.notes }).eq('id', order.id); if (error) throw error; await loadAll(); status(order.admin_hold ? 'Manual hold released.' : 'Order placed on manual hold.', 'success'); }
    } catch (error) { status(error.message, 'error'); if (send) send.disabled = false; if (sync) sync.disabled = false; }
  }
  function csvCell(value) { return `"${String(value ?? '').replace(/"/g, '""')}"`; }
  function exportOrders() { const headers = ['Order number','Created','Customer','Phone','Email','Address','Items','Subtotal','Shipping','Total','Payment status','Razorpay payment ID','Fulfilment status','Printrove order ID','Printrove status','Admin hold']; const rows = orders.map((order) => [order.order_number,order.created_at,order.customer_name,order.customer_phone,order.customer_email,[order.address_line1,order.address_line2,order.city,order.state,order.pincode].filter(Boolean).join(', '),(order.order_items||[]).map((item)=>`${item.quantity}x ${item.product_name} ${item.colour}/${item.size}`).join('; '),order.subtotal,order.shipping_amount,order.total_amount,order.payment_status,order.razorpay_payment_id,order.fulfilment_status,order.printrove_order_id,order.printrove_status,order.admin_hold].map(csvCell).join(',')); download(`veyrath-orders-${new Date().toISOString().slice(0,10)}.csv`, `\uFEFF${headers.map(csvCell).join(',')}\n${rows.join('\n')}`, 'text/csv;charset=utf-8'); }

  function populateHomepage() { const form = $('#homepageForm'); const hero = siteData.hero || {}; const values = { hero_eyebrow:hero.eyebrow,hero_heading:hero.heading,hero_subheading:hero.subheading,primary_label:hero.primary_label,primary_link:hero.primary_link,secondary_label:hero.secondary_label,secondary_link:hero.secondary_link,hero_image:hero.image_url,about_text:siteData.about_text,marquee_text:siteData.marquee_text,category_intro:siteData.category_intro }; Object.entries(values).forEach(([key,value]) => { if (form.elements[key]) form.elements[key].value = value || ''; }); }
  async function submitHomepage(event) { event.preventDefault(); const form = event.currentTarget; const v = Object.fromEntries(new FormData(form)); siteData.hero = { ...(siteData.hero||{}),eyebrow:v.hero_eyebrow.trim(),heading:v.hero_heading.trim(),subheading:v.hero_subheading.trim(),primary_label:v.primary_label.trim(),primary_link:v.primary_link.trim(),secondary_label:v.secondary_label.trim(),secondary_link:v.secondary_link.trim(),image_url:v.hero_image.trim() }; siteData.about_text=v.about_text.trim(); siteData.marquee_text=v.marquee_text.trim(); siteData.category_intro=v.category_intro.trim(); const { error } = await client.from('site_settings').upsert({ key:'site_data',value:siteData,is_public:true }); message(form,error?error.message:'Homepage saved.'); }
  function renderBanners() { const banners=siteData.banners||[]; $('#bannerList').innerHTML=banners.map((b)=>`<div class="banner-row"><img src="${esc(b.image_url||'veyrath-hero.jpg')}" alt=""><div><strong>${esc(b.heading)}</strong><small>${esc(b.eyebrow||'')}</small></div><button class="danger" type="button" data-delete-banner="${b.id}">Remove</button></div>`).join('')||'<p>No banners yet.</p>'; }
  async function submitBanner(event) { event.preventDefault(); const form=event.currentTarget; const v=Object.fromEntries(new FormData(form)); const { error }=await client.from('hero_slides').insert({eyebrow:v.eyebrow.trim(),heading:v.heading.trim(),body:v.text.trim(),image_url:v.image_url.trim(),align:v.align||'left',is_published:true,sort_order:(siteData.banners||[]).length}); if(error)return message(form,error.message); form.reset(); await loadAll(); message(form,'Carousel banner added.'); }
  function renderRecords() { $('#inquiryList').innerHTML=inquiries.map((x)=>`<article class="data-row"><small>${new Date(x.created_at).toLocaleString('en-IN')} · ${esc(x.subject||'Inquiry')}</small><strong>${esc(x.name||'Anonymous')} · ${esc(x.email||'')}</strong><span>${esc(x.product||'')}</span><p>${esc(x.message||'')}</p></article>`).join('')||'<p>No inquiries yet.</p>'; $('#newsletterList').innerHTML=newsletter.map((x)=>`<article class="data-row"><small>${new Date(x.created_at).toLocaleString('en-IN')}</small><strong>${esc(x.email)}</strong></article>`).join('')||'<p>No newsletter signups yet.</p>'; }
  function renderAll() { $('#statProducts').textContent=products.length; $('#statPublished').textContent=products.filter((p)=>p.is_published).length; $('#statOrders').textContent=orders.length; $('#statPaid').textContent=orders.filter((o)=>o.payment_status==='paid').length; $('#statPrintrove').textContent=orders.filter((o)=>['not_sent','printrove_failed'].includes(o.fulfilment_status)&&o.payment_status==='paid').length; $('#statHolds').textContent=orders.filter((o)=>o.admin_hold).length; renderProducts(); renderOrders(); populateHomepage(); renderBanners(); renderRecords(); }

  function download(name,text,type='text/javascript') { const url=URL.createObjectURL(new Blob([text],{type})); const anchor=document.createElement('a'); anchor.href=url; anchor.download=name; anchor.click(); setTimeout(()=>URL.revokeObjectURL(url),500); }
  async function importData(event) { event.preventDefault(); const form=event.currentTarget; try { const parsed=JSON.parse($('#importJson').value); const imported=Array.isArray(parsed)?parsed:parsed.products; if(Array.isArray(imported)&&imported.length){ const normalized=imported.map((p)=>({...p,id:/^[0-9a-f-]{36}$/i.test(p.id||'')?p.id:uuid()})); const {error}=await client.from('products').upsert(normalized); if(error)throw error; } if(parsed.siteData){const {error}=await client.from('site_settings').upsert({key:'site_data',value:parsed.siteData,is_public:true});if(error)throw error;} await loadAll();message(form,'Data imported.'); } catch(error){message(form,`Import failed: ${error.message}`);} }

  function bind() {
    ensureLoginHelpers(); $('#loginForm').addEventListener('submit',login); $('#adminMagicLink').addEventListener('click',magicLink); $('#adminClearSession').addEventListener('click',clearSession); $('#adminLogout').addEventListener('click',async()=>{await client?.auth.signOut();openLogin('Signed out.');});
    $$('.admin-nav button').forEach((button)=>button.addEventListener('click',()=>activate(button.dataset.adminTab))); $$('[data-admin-tab-jump]').forEach((button)=>button.addEventListener('click',()=>activate(button.dataset.adminTabJump)));
    $('#productForm').addEventListener('submit',submitProduct); $('#productReset').addEventListener('click',resetProduct); ['price','selling_price','base_cost','shipping_cost'].forEach((name)=>$('#productForm').elements[name].addEventListener('input',updateProfit));
    $('#productsTable').addEventListener('click',async(event)=>{const edit=event.target.closest('[data-edit-product]');const toggle=event.target.closest('[data-toggle-product]');const remove=event.target.closest('[data-delete-product]');if(edit)editProduct(edit.dataset.editProduct);if(toggle){const p=products.find((x)=>x.id===toggle.dataset.toggleProduct);const{error}=await client.from('products').update({is_published:!p.is_published}).eq('id',p.id);if(!error)await loadAll();}if(remove){const p=products.find((x)=>x.id===remove.dataset.deleteProduct);if(p&&confirm(`Delete “${p.name}”?`)){const{error}=await client.from('products').delete().eq('id',p.id);if(error)alert(error.message);else await loadAll();}}});
    $('#ordersTable').addEventListener('click',orderAction); $('#orderFilter').addEventListener('change',renderOrders); $('#refreshOrders').addEventListener('click',loadAll); $('#exportOrdersCsv').addEventListener('click',exportOrders);
    $('#homepageForm').addEventListener('submit',submitHomepage); $('#bannerForm').addEventListener('submit',submitBanner); $('#bannerList').addEventListener('click',async(event)=>{const button=event.target.closest('[data-delete-banner]');if(button){const{error}=await client.from('hero_slides').delete().eq('id',button.dataset.deleteBanner);if(!error)await loadAll();}});
    $('#importForm').addEventListener('submit',importData); $('#exportProducts').addEventListener('click',()=>download('products.js',`(function(){window.VEYRATH_PRODUCTS=${JSON.stringify(products,null,2)};})();\n`)); $('#exportSite').addEventListener('click',()=>download('site-data.js',`(function(){window.VEYRATH_SITE_DATA=${JSON.stringify(siteData,null,2)};})();\n`)); $('#exportJson').addEventListener('click',()=>download('veyrath-data.json',JSON.stringify({products,siteData},null,2),'application/json')); $('#clearLocalData').addEventListener('click',()=>{['veyrath_products_v3','veyrath_site_data_v3','veyrath_inquiries_v3','veyrath_newsletter_v3'].forEach((key)=>localStorage.removeItem(key));message($('#importForm'),'Browser catalogue cache cleared.');});
  }
  async function init() { bind(); try { if(!(await connectClient())) return openLogin('Configure supabase-config.js to enable secure admin login.'); const {data}=await client.auth.getSession(); if(data.session&&await isAdmin())return openApp(); openLogin(); } catch(error){openLogin(`Could not connect to Supabase: ${error.message}`);} }
  init();
})();
